//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ManagerTool.rc 使用
//
#define IDC_MODIFY_INSURE_PASSWORD      2
#define IDC_QUERY_INFO                  2
#define IDC_LEAVE_GAME                  3
#define IDC_DEFAULT                     3
#define IDCANCEL2                       3
#define IDC_CLOSE_PLAZA                 4
#define IDR_MAINFRAME                   128
#define IDS_FRAME_TITLE                 129
#define IDR_COMMAND                     166
#define IDD_DLG_STATUS                  168
#define IDC_HAND_CUR                    217
#define IDI_SEARCH                      347
#define IDI_WHISPER                     348
#define IDI_NULL                        350
#define IDI_KING                        373
#define IDD_DLG_LOGON                   385
#define IDD_PLATFORM_FRAME              386
#define IDD_GAME_PLAZA                  386
#define IDB_BITMAP1                     396
#define IDD_TABLE_PASSWORD              397
#define IDI_ICON1                       398
#define IDR_PNG1                        405
#define IDR_PNG2                        406
#define IDC_EDIT_AMOUNT                 420
#define IDR_ANI1                        420
#define ANI_GAME_LOAD                   420
#define IDC_EDIT_BANKPASS               421
#define IDC_BTN_STORAGE                 422
#define IDC_CUR_GOLD                    424
#define IDC_BANK_GOLD                   425
#define IDC_EDIT_RECV_ACCOUNT           426
#define IDC_EDIT_AMOUNT2                426
#define IDC_BANK_GOLD2                  426
#define IDC_TAKE_TIMES                  426
#define IDC_BTN_TRANSFER                427
#define IDR_ANI2                        427
#define IDC_RADIO_ACCOUNT               428
#define IDC_RADIO_GAMEID                429
#define IDC_STATIC_TYPE                 430
#define IDD_BATCH_VIEW                  435
#define IDD_BATCH_OPTION                435
#define IDD_SERVER_OPTION               435
#define IDD_BATCH_VIEW1                 436
#define IDD_CUSTOM_VIEW                 436
#define IDD_CUSTOM_OPTION               436
#define IDC_SELECT_FACE                 1000
#define IDC_FACE_ITEM                   1001
#define IDC_USER_NAME                   1002
#define IDC_MAIN_STATION                1003
#define IDC_AREA_INFO_NOTE              1004
#define IDC_WEB_STOP                    1005
#define IDC_TABLE_PASSWORD              1006
#define IDC_FIREND_CENTER               1007
#define IDC_WEB_RELOAD                  1008
#define IDC_WEB_HOME                    1009
#define IDC_SEARCH_ONE_NULL             1010
#define IDC_GIVE_UP                     1011
#define IDC_REM_PASSWORD                1012
#define IDC_PROGRESS                    1013
#define IDC_SEARCH_TWO_NULL             1014
#define IDC_DELETE_RECORD               1015
#define IDC_STATUS                      1016
#define IDC_SEARCH_NOT_FULL             1017
#define IDC_USER_ID                     1018
#define IDC_SEARCH_ALL_NULL             1019
#define IDC_PROXY_OPTION                1020
#define IDC_WEB_LAST                    1021
#define IDC_FILTRATE_PASS               1022
#define IDC_REGISTER                    1023
#define IDC_WEB_NEXT                    1024
#define IDC_PROVINCE                    1025
#define IDC_CITY                        1026
#define IDC_AREA                        1027
#define IDC_GAME_REVENUE                1027
#define IDC_ACCOUNTS_SERVICE            1028
#define IDC_GET_PASSWORD                1029
#define IDC_LIST_NORMAL                 1030
#define IDC_PROXY_TEST                  1031
#define IDC_LIST_CUSTOM                 1032
#define IDC_PROXY_TYPE                  1033
#define IDC_PROXY_SERVER                1034
#define IDC_CHAT_MESSAGE                1035
#define IDC_PROXY_USER                  1036
#define IDC_EDT_HISTORY                 1036
#define IDC_VIEW_CONTROL                1037
#define IDC_PROXY_PORT                  1038
#define IDC_USER_NORMAL                 1039
#define IDC_PROXY_PASS                  1040
#define IDC_USER_CUSTOM                 1041
#define IDC_BORDER                      1042
#define IDC_USER_COMPETITION            1043
#define IDC_GAME_ID                     1044
#define IDC_QUIT_GAME                   1045
#define IDC_PLAZA_HELP                  1046
#define IDC_CALL_MASTER                 1047
#define IDC_TYPE_NAME                   1048
#define IDC_AUTO_JOIN                   1049
#define IDC_SEARCH_USER                 1050
#define IDC_TYPE_NAME2                  1051
#define IDC_VIEW_MODE                   1052
#define IDC_JOIN_MENU                   1053
#define IDC_EDIT_TABLE_NUM              1053
#define IDC_TAKE_PASSWORD               1054
#define IDC_CHAT_EDIT                   1055
#define IDC_SEND_CHAT                   1056
#define IDC_CHECK_SERVICE_MODE2         1056
#define IDC_ACCOUNTS                    1057
#define IDC_CHECK_SERVICE_MODE3         1057
#define IDC_SERVER_MANAGE               1058
#define IDC_QQ                          1058
#define IDC_PASSPORT_ID                 1058
#define IDC_EDT_PASSPORT                1058
#define IDC_PASSWORD                    1059
#define IDC_SECRET_TABLE                1059
#define IDC_CHECK_SERVICE_MODE4         1059
#define IDC_EXPRESSION                  1060
#define IDC_LOGON_PASSWORD2             1060
#define IDC_EMAIL                       1060
#define IDC_RESPONSE                    1060
#define IDC_EDT_SPREADER                1060
#define IDC_PASSWORD2                   1061
#define IDC_LOGON_PASSWORD3             1061
#define IDC_SEAT_PHONE                  1061
#define IDC_PASSPORT_ID_CONFIRM         1061
#define IDC_COMBO_GAME                  1061
#define IDC_COMBO_GAME_LIST             1061
#define IDC_BUGLE                       1062
#define IDC_INSURE_PASSWORD2            1062
#define IDC_MOBILE_PHONE                1062
#define IDC_SAFE_EMAIL                  1062
#define IDC_PASSWORD3                   1062
#define IDC_COMBO_SERVER                1062
#define IDC_COMBO_SERVER_LIST           1062
#define IDC_LOGON_SERVER                1063
#define IDC_INSURE_PASSWORD3            1063
#define IDC_DWELLING_PLACE              1063
#define IDC_SAFE_EMAIL_CONFIRM          1063
#define IDC_PASSWORD4                   1063
#define IDC_BT_QUERY                    1063
#define IDC_COMBO_SERVER_TYPE           1063
#define IDC_COLOR_SET                   1064
#define IDC_RESPONSE2                   1064
#define IDC_VALIDATE_CODE               1064
#define IDC_LIST_PARAMETER              1064
#define IDC_LAST                        1065
#define IDC_USER_NOTE                   1065
#define IDC_RESPONSE3                   1065
#define IDC_EDIT_ROBOT_COUNT            1065
#define IDC_LIST_JACKPOT_LIST           1065
#define IDC_LIST_JACKPOT_INFO           1065
#define IDC_LIST_WHITELIST_WEIGHT       1065
#define IDC_SAVE_CHAT                   1066
#define IDC_COMBO_ENTER_HOUR            1066
#define IDC_NEXT                        1067
#define IDC_COMBO_ENTER_MINUTE          1067
#define IDC_CLEAN_SCREEN                1068
#define IDC_COMBO_ENTER_SECOND          1068
#define IDC_MORE_FUNCTION               1069
#define IDC_COMBO_LEAVE_HOUR            1069
#define IDC_STOP_CHAT                   1070
#define IDC_COMBO_LEAVE_MINUTE          1070
#define IDC_VOR_SPLITER                 1071
#define IDC_COMBO_LEAVE_SECOND          1071
#define IDC_ITEM_FRAME                  1072
#define IDC_EDIT_ENTERINTERVAL_MIN      1072
#define IDC_COMBO_ENTER_HOUR2           1072
#define IDC_COMBO_SERVICE_MODE          1072
#define IDC_HOR_SPLITER                 1073
#define IDC_EDIT_ENTERINTERVAL_MAX      1073
#define IDC_EDIT_LEAVEINTERVAL_MIN      1074
#define IDC_COMBO_GAME_KIND             1074
#define IDC_LIST_REMOTE                 1075
#define IDC_EDIT_LEAVEINTERVAL_MAX      1075
#define IDC_FINISH                      1076
#define IDC_EDIT_SWITCHTABLE_MIN        1076
#define IDC_SERVICE_ARTICLE             1077
#define IDC_EDIT_SWITCHTABLE_MAX        1077
#define IDC_LIST_NATIVE                 1078
#define IDC_EDIT_TAKESCORE_MIN          1078
#define IDC_LIMIT_SAME_IP               1079
#define IDC_EDIT_TAKESCORE_MAX          1079
#define IDC_SWITCH_ACCOUNTS             1080
#define IDC_BT_ADD                      1080
#define IDC_EDIT_DRAW_COUNT_MIN         1080
#define IDC_LIMIT_FLEE_RATE             1081
#define IDC_BT_MODIFY                   1081
#define IDC_EDIT_DRAW_COUNT_MAX         1081
#define IDC_CHAT_SHORT                  1082
#define IDC_BT_DELETE                   1082
#define IDC_EDIT_DRAW_TIME_MIN          1082
#define IDC_EDIT_ROBOT_COUNT_MAX        1082
#define IDC_LIMIT_GAME_SCORE            1083
#define IDC_RADIO1                      1083
#define IDC_EDIT_DRAW_COUNT_MAX2        1083
#define IDC_EDIT_DRAW_TIME_MAX          1083
#define IDC_EDIT_UPDATE_COUNT_MAX       1083
#define IDC_LIMIT_WINRATE               1083
#define IDC_EDIT_COUNT_MEMBER0          1083
#define IDC_RADIO_AUTO_MODE             1083
#define IDC_RADIO_LOST                  1083
#define IDC_CHAT_HISTORY                1084
#define IDC_SWITCH_BY_TIME              1084
#define IDC_RADIO3                      1084
#define IDC_ALLOW_WINRATE               1084
#define IDC_RADIO_TIME_CONTROL          1084
#define IDC_RADIO_MANUAL_MODE           1084
#define IDC_RADIO_WIN                   1084
#define IDC_ADD_USER                    1085
#define IDC_RADIO4                      1085
#define IDC_LIMIT_FLEERATE              1085
#define IDC_BT_APPEND_JACKPOT           1085
#define IDC_LEAVE_CHAT                  1086
#define IDC_RADIO5                      1086
#define IDC_ALLOW_FLEERATE              1086
#define IDC_BT_MODIFY2                  1086
#define IDC_BT_MODIFY_JACKPOT           1086
#define IDC_USER_LIST                   1087
#define IDC_RADIO6                      1087
#define IDC_LIMIT_IPSET                 1087
#define IDC_BT_DELETE2                  1087
#define IDC_BT_DELETE_JACKPOT           1087
#define IDC_LIMIT_DETEST                1088
#define IDC_SHIELD_THIS_CHAT            1088
#define IDC_RADIO7                      1088
#define IDC_ALLOW_IPSET                 1088
#define IDC_SEND_CONTROL                1089
#define IDC_RADIO8                      1089
#define IDC_LIMIT_SCORELIMIT            1089
#define IDC_ADD_FRIEND                  1090
#define IDC_RADIO9                      1090
#define IDC_ALLOW_SCORELIMIT            1090
#define IDC_CHAT_SPLITTER               1091
#define IDC_RADIO10                     1091
#define IDC_LIMIT_PASSWORD              1091
#define IDC_WIN_RATE                    1092
#define IDC_HISTORY_SPLITTER            1092
#define IDC_RADIO11                     1092
#define IDC_ALLOW_PASSWORD              1092
#define IDC_INFO_SPLITTER               1093
#define IDC_RADIO12                     1093
#define IDC_LIMIT_BLACK                 1093
#define IDC_ITEM_TAB                    1094
#define IDC_SHIELD_THIS_CHAT3           1094
#define IDC_RECV_NO_PROP                1094
#define IDC_SET_DETEST                  1094
#define IDC_RADIO13                     1094
#define IDC_ALLOW_BLACK                 1094
#define IDC_GAME_SCORE_LESS             1095
#define IDC_SEND_CONTROL2               1095
#define IDC_USER_MENU                   1095
#define IDC_RADIO14                     1095
#define IDC_LIMIT_WISPER                1095
#define IDC_LIMIT_BASE_SCORE            1095
#define IDC_MODE_ACCOUNTS               1096
#define IDC_MESSAGE_SETTING             1096
#define IDC_RADIO15                     1096
#define IDC_ALLOW_WISPER                1096
#define IDC_ALLOW_BASE_SCORE            1096
#define IDC_MODE_GAME_ID                1097
#define IDC_RADIO16                     1097
#define IDC_LIMIT_GAME_CHAT             1097
#define IDC_SAVE_NONE                   1098
#define IDC_RADIO17                     1098
#define IDC_ALLOW_GAME_CHAT             1098
#define IDC_SAVE_ACCOUNTS               1099
#define IDC_RADIO18                     1099
#define IDC_LIMIT_ROOM_CHAT             1099
#define IDC_RADIO19                     1100
#define IDC_SAVE_ACCOUNTS_AND_PASS      1101
#define IDC_RADIO20                     1101
#define IDC_LIMIT_PLAY_CHAT             1101
#define IDC_POINT                       1102
#define IDC_RADIO21                     1102
#define IDC_ALLOW_PLAY_CHAT             1102
#define IDC_WIN                         1103
#define IDC_RADIO22                     1103
#define IDC_LIMIT__MEMBER_CHAT          1103
#define IDC_LIMIT_MEMBER_CHAT           1103
#define IDC_ALL_COUNT                   1104
#define IDC_RADIO23                     1104
#define IDC_ALLOW__MEMBER_CHAT          1104
#define IDC_ALLOW_MEMBER_CHAT           1104
#define IDC_PUBLICIZE_LOGO              1105
#define IDC_RADIO24                     1105
#define IDC_LIMIT_LOOKON_CHAT           1105
#define IDC_LOST                        1106
#define IDC_RADIO25                     1106
#define IDC_ALLOW_LOOKON_CHAT           1106
#define IDC_USER_INFO_MENU              1107
#define IDC_RADIO26                     1107
#define IDC_LIMIT_ENTER_ROOM            1107
#define IDC_MESSAGE_SHOW_ALL            1108
#define IDC_RADIO27                     1108
#define IDC_ALLOW_ENTER_ROOM            1108
#define IDC_MESSAGE_ONLY_FRIEND         1109
#define IDC_RADIO28                     1109
#define IDC_LIMIT_ROBOT_SIMULATE        1109
#define IDC_MESSAGE_ONLY_FRIEND2        1110
#define IDC_MESSAGE_HIDE_ALL            1110
#define IDC_RADIO29                     1110
#define IDC_ALLOW_ROBOT_SIMULATE        1110
#define IDC_MESSAGE_HIDE_DETEST         1111
#define IDC_RADIO30                     1111
#define IDC_LIMIT_ENTER_GAME            1111
#define IDC_LIMIT_GAME_VIDEO            1111
#define IDC_RADIO31                     1112
#define IDC_ALLOW_ENTER_GAME            1112
#define IDC_INVITE_ALL                  1113
#define IDC_RADIO32                     1113
#define IDC_LIMIT_ROBOT_ATTEND          1113
#define IDC_RADIO33                     1114
#define IDC_ALLOW_ROBOT_ATTEND          1114
#define IDC_INVITE_ONLY_FRIEND          1115
#define IDC_RADIO34                     1115
#define IDC_LIMIT_LOOKON                1115
#define IDC_RADIO35                     1116
#define IDC_ALLOW_LOOKON                1116
#define IDC_GAME_SCORE_MAX              1117
#define IDC_RADIO36                     1117
#define IDC_LIMIT_BASEENSURE            1117
#define IDC_INVITE_NONE                 1118
#define IDC_RADIO37                     1118
#define IDC_ALLOW_BASEENSURE            1118
#define IDC_RADIO38                     1119
#define IDC_LIMIT_IMMEDIATE_WRITE_SCORE 1119
#define IDC_AUTO_SHOW_WHISPER           1120
#define IDC_RADIO39                     1120
#define IDC_ALLOW_IMMEDIATE_WRITE_SCORE 1120
#define IDC_SHOW_WHISPER_BY_HOTKEY      1121
#define IDC_RADIO40                     1121
#define IDC_LIMIT_RECORD_GAME_SCORE     1121
#define IDC_WHISPER_HOTKEY              1122
#define IDC_RADIO41                     1122
#define IDC_ALLOW_RECORD_GAME_SCORE     1122
#define IDC_NOTIFY_USER_INOUT           1123
#define IDC_LIMIT_VOICE_CHAT            1123
#define IDC_ALLOW_IMMEDIATE_WRITE_SCORE2 1124
#define IDC_ALLOW_VOICE_CHAT            1124
#define IDC_FULL_SCREEN_BROWSE          1125
#define IDC_STOP_CLUB_SERVICE           1125
#define IDC_SNED_WHISPER_BY_ENTER       1126
#define IDC_FULL_SCREEN_BROWSE2         1126
#define IDC_SHOW_SAFE_PROMPT            1126
#define IDC_START_CLUB_SERVICE          1126
#define IDC_AUTO_SAVE_WHISPER           1127
#define IDC_RADIO46                     1127
#define IDC_LIMIT_OFFLINE_STANDUP       1127
#define IDC_SNED_WHISPER_BY_CTRL_ENTER  1128
#define IDC_RADIO47                     1128
#define IDC_ALLOW_OFFLINE_STANDUP       1128
#define IDC_AUTO_SIT_DOWN               1129
#define IDC_ALLOW_DYNAMIC_JOINGAME      1129
#define IDC_LIMIT_DYNAMIC_JOINGAME      1130
#define IDC_SALIENCE_TABLE              1131
#define IDC_RADIO50                     1131
#define IDC_LIMIT__FORCE_STANDUP        1131
#define IDC_LIMIT_FORCE_STANDUP         1131
#define IDC_RADIO51                     1132
#define IDC_ALLOW__FORCE_STANDUP        1132
#define IDC_ALLOW_FORCE_STANDUP         1132
#define IDC_NOTIFY_FRIEND_COME          1133
#define IDC_ALLOW_GAME_VIDEO            1134
#define IDC_BOSS_HOTKEY                 1135
#define IDC_ACTION_SEND_WHISPER         1137
#define IDC_TABLE_VIEW                  1139
#define IDC_ACTION_SHOW_USER_INFO       1140
#define IDC_ACTION_SEARCH_TABLE         1141
#define IDC_SHOW_SEARCH_TABLE_DLG       1142
#define IDC_ACTION_ORIENTATION          1143
#define IDC_SEARCH_KEY                  1144
#define IDC_INVATE_TIME                 1145
#define IDC_SEARCH_MODE                 1146
#define IDC_GAME_ORDER                  1147
#define IDC_BUTTON2                     1148
#define IDC_DISMISS_GAME                1148
#define IDC_DRAW                        1151
#define IDC_ENTER                       1154
#define IDC_APPLY_POLICY                1156
#define IDC_FLEE_RATE                   1158
#define IDC_LOAD_POLICY                 1159
#define IDC_FULL_CONTROL                1160
#define IDC_SERVICE_TIME                1161
#define IDC_SIT_DOWN                    1162
#define IDC_MAX_COUNT                   1163
#define IDC_STAND_UP                    1164
#define IDC_OFF_LINE                    1165
#define IDC_TAKE_OVER                   1166
#define IDC_UNDER_WRITE                 1168
#define IDC_WEB_BROWSE                  1174
#define IDC_SELECT_LINK                 1177
#define IDC_AGE                         1178
#define IDC_GENDER                      1179
#define IDC_QUESTION                    1180
#define IDC_LOGON_PASSWORD1             1181
#define IDC_QUESTION2                   1181
#define IDC_INSURE_PASSWORD1            1182
#define IDC_QUESTION3                   1182
#define IDC_MODIFY_LOGON_PASSWORD       1183
#define IDC_NOTE                        1184
#define IDC_COMPELLATION                1185
#define IDC_SKIN_LIST                   1186
#define IDC_PUBLICIZE_STATIC            1188
#define IDC_KICK_ALL_USER               1191
#define IDC_EDT_MESSAGE                 1192
#define IDC_ISSUE_MESSAGE               1193
#define IDC_CHECK2                      1195
#define IDC_CHEK_GAME                   1197
#define IDC_CHEK_ROOM                   1198
#define IDC_ADD_PASSWORD                1199
#define IDC_EXIT_LOCK                   1200
#define IDC_EXIT_LOCK2                  1201
#define IDC_EXIT_UNLOCK                 1201
#define IDC_PROMPT_STRING               1201
#define IDC_PASSPORT_TYPE               1202
#define IDC_LINK                        1203
#define IDC_PROMPT                      1204
#define IDC_PROMPT_LOCKED               1205
#define IDC_PROMPT_UNLOCK               1206
#define IDC_LOCK                        1207
#define IDC_UNLOCK                      1208
#define IDC_PROMPT_MEMBER               1210
#define IDC_JOIN_MEMBER                 1211
#define IDC_CHECK1                      1212
#define IDC_CHK_LOCK                    1212
#define IDC_CHECK_NEVER_PROMPT          1212
#define IDC_CB_PASSPORT                 1213
#define IDC_ST_SPREADER                 1214
#define IDC_STATIC1                     1215
#define IDC_STATIC2                     1216
#define IDC_STATIC3                     1217
#define IDC_STATIC4                     1218
#define IDC_STATIC5                     1219
#define IDC_EDT_ORG_ACCOUNT             1220
#define IDC_EDT_ORG_PASSWORD            1221
#define IDC_ACTIVATE_TIPS               1222
#define IDC_ACTIVATE_URL                1223
#define IDC_ACTIVATE_ICON               1224
#define IDC_BTN_TEST_ACCOUNT            1225
#define IDC_BTN_PROTECT                 1226
#define IDC_BTN_TEST_NICKNAME           1226
#define IDC_BTN_BIND                    1227
#define IDC_RADIO_STORAGE               1229
#define IDC_RADIO2                      1230
#define IDC_RADIO_DRAWOUT               1230
#define IDC_STATIC_BANK_PROMPT          1231
#define IDC_STATIC_PROMPT               1232
#define IDC_NICKNAME                    1235
#define IDC_TAB_LOGON                   1236
#define IDC_VALIDATE_CODE_WND           1239
#define IDC_BT_CHANGE_VALIDATE          1241
#define IDC_BUTTON1                     1242
#define IDC_BT_ENTER_ROOM               1242
#define IDC_BT_APPEND                   1242
#define IDC_EDIT_SITDOWN_TIME_MIN       1243
#define IDC_BT_EXIT_ROOM                1243
#define IDC_BT_SAVE_NORMAL_TABLE        1243
#define IDC_EDIT_LOGONPASS              1244
#define IDC_EDIT_SITDOWN_TIME_MAX       1244
#define IDC_BT_EXIT_ROOM2               1244
#define IDC_BT_CARD_DISPATCHER          1244
#define IDC_BT_SAVE_WHITELIST_TABLE     1244
#define IDC_EDIT_INVALIDATE_CODE        1245
#define IDC_EDIT_STANDUP_TIME_MIN       1245
#define IDC_BT_ROOM_MANAGE              1245
#define IDC_BT_GAME_DEBUG               1245
#define IDC_BTN_TAKE                    1246
#define IDC_BTN_TAKE_BASEENSURE         1246
#define IDC_EDIT_STANDUP_TIME_MAX       1246
#define IDC_BT_ROOM_MANAGE2             1246
#define IDC_BT_MANAGE_CMD               1246
#define IDC_BT_GAME_DEBUG2              1246
#define IDC_BT_ROBOT_DEBUG              1246
#define IDC_BT_SAVE_BASIC_CONFIG        1246
#define IDC_INVALIDATE_CODE             1247
#define IDC_EDIT_READYWAIT_TIME_MIN     1247
#define IDC_BT_AI_MANAGER               1247
#define IDC_BT_REFRESH_VALIDATE         1248
#define IDC_EDIT_READYWAIT_TIME_MAX     1248
#define IDC_TAKE_CONDITION              1249
#define IDC_SWITCH_BY_COUNT             1249
#define IDC_TAKE_AMOUNT                 1250
#define IDC_EDIT_SWITCHTABLE_VALUE_MIN  1250
#define IDC_EDIT_SWITCHTABLE_VALUE_MAX  1251
#define IDC_ROBOT_OPTION                1252
#define IDC_EDIT_LOOKON_RATE_MIN        1252
#define IDC_ROBOT_VIEW                  1253
#define IDC_EDIT_LOOKON_RATE_MAX        1253
#define IDC_MANAGER_OPTION              1253
#define IDC_EDIT_ROBOT_COUNT_MIN        1254
#define IDC_EDIT_LOOKON_TIME_MIN        1254
#define IDC_EDIT_UPDATE_COUNT_MIN       1255
#define IDC_EDIT_LOOKON_TIME_MAX        1255
#define IDC_BT_EXECUTE_CMD              1259
#define IDC_LOAD_GAME_VERSION           1260
#define IDC_LOAD_PLAZA_VERSION          1261
#define IDC_LOAD_PLAZA_VERSION2         1262
#define IDC_LOAD_CREATE_OPTION          1262
#define IDC_BT_RELOAD_CONFIG            1262
#define IDC_LOAD_ALLOW_ADDRESS          1263
#define IDC_LOAD_PLAZA_VERSION3         1264
#define IDC_STOP_CREATE_TABLE           1264
#define IDC_BATTLE_SERVICE              1264
#define IDC_STOP_BATTLE_SERVICE         1265
#define IDC_CLUB_SERVICE                1266
#define IDC_START_BATTLE_SERVICE        1267
#define IDC_LOAD_ALLOW_ADDRESS2         1268
#define IDC_LOAD_CLUB_OPTION            1268
#define IDC_UNLOAD_CLUB_DATA            1268
#define IDC_RELOAD_CLUB_DATA            1268
#define IDC_LOAD_CREATE_OPTION2         1269
#define IDC_LOAD_FORBID_WORDS           1269
#define IDC_LOAD_CLUB_OPTION2           1270
#define IDC_OUTPUT_DEBUG_INFO           1270
#define IDC_UNLOAD_CLUB_DATA2           1270
#define IDC_PRINT_CLUB_INFO             1270
#define IDC_MATCH_SERVICE               1271
#define IDC_STOP_MATCH_SERVICE          1272
#define IDC_START_BATTLE_SERVICE2       1273
#define IDC_START_MATCH_SERVICE         1273
#define IDC_LOAD_MATCH_OPTION           1274
#define IDC_LOAD_GAME_LIST              1275
#define IDC_LOAD_GAME_LEVEL             1276
#define IDC_LOAD_GAME_GOODS             1277
#define IDC_LOAD_SUBSIDY_PARAM          1278
#define IDC_LOAD_ROBOT_PARAM            1279
#define IDC_LOAD_CONTROL_PARAM          1280
#define IDC_LIST2                       1281
#define IDC_USER_LIST_CONTROL           1281
#define IDC_LOAD_BATTLE_OPTION          1281
#define IDC_LIST1                       1282
#define IDC_LOAD_TRANSFER_PARAM         1283
#define IDC_LOAD_GAME_BASIC_CONFIG      1284
#define IDC_LOAD_GAME_WEIGHT_CONFIG     1285
#define IDC_LOAD_TURNTABLE_CONFIG       1286
#define IDC_EDIT_STOCK_ID               1286
#define IDC_LOAD_MARQUEE_CONFIG         1287
#define IDC_EDIT_KIND_ID                1287
#define IDC_LOAD_GAME_VERSION2          1288
#define IDC_EDIT_STOCK_KIND             1288
#define IDC_LOAD_STOCK_CONFIG           1288
#define IDC_EDIT_BET_AMOUNT             1289
#define IDC_LOAD_SUPER_PLAYER_CONFIG    1289
#define IDC_LOAD_SPLAYER_CONFIG         1289
#define IDC_EDIT_STOCK_NAME             1290
#define IDC_EDIT_STOCK_LEVEL            1291
#define IDC_EDIT_KIND_ID2               1292
#define IDC_EDIT_STOCK_SCORE            1292
#define IDC_EDIT_EXTRA_SCORE            1293
#define IDC_EDIT_JACKPOT_LEVELID        1294
#define IDC_EDIT_JACKPOT_SCORE          1295
#define IDC_EDIT_VIRTUAL_SCORE2         1296
#define IDC_EDIT_VIRTUAL_SCORE          1296
#define IDC_EDIT_JACKPOT_EXTRA_SCORE3   1297
#define IDC_EDIT_JACKPOT_EXTRA_SCORE    1297
#define IDC_EDIT_SHRINK_RATIO           1298
#define IDC_EDIT_PAYOUT_PROB            1299
#define IDC_EDIT_PAYOUT_LIMIT           1300
#define IDC_EDIT_SHRINK_OPTION          1301
#define IDC_EDIT_RELATION_ID_LIST       1302
#define IDC_DATE_START_DATE             1303
#define IDC_DATETIMEPICKER2             1304
#define IDC_DATE_START_TIME             1304
#define IDC_DATE_END_DATE               1305
#define IDC_DATE_END_TIME               1306
#define IDC_LIST_STOCK_LIST             1307
#define IDC_LIST_STOCK_INFO             1307
#define IDC_EDIT_PAYOUT_ORIGIN          1308
#define IDC_EDIT_JACKPOT_SCORE2         1309
#define IDC_EDIT_INITIAL_SCORE2         1309
#define IDC_EDIT_INITIAL_SCORE          1309
#define IDC_COMBO_GAME_NAME             1310
#define IDC_BT_APPEND_STOCK             1311
#define IDC_BT_MODIFY_STOCK             1312
#define IDC_BT_DELETE_STOCK             1313
#define IDC_EDIT_STOCK_STATE            1314
#define IDC_BT_QUERY_STOCK              1315
#define IDC_COMBO1                      1316
#define IDC_BT_DELETE_STOCK2            1316
#define IDC_BT_CONFIRM                  1316
#define IDC_COMBO_WEIGHT_TYPE           1316
#define IDC_EDIT_BASIC_CONFIG           1317
#define IDC_COMBO_GAME_NAME2            1317
#define IDC_COMBO_STOCK_LEVEL           1317
#define IDC_LIST_NORMAL_WEIGHT          1318
#define IDC_EDIT_MIN_TIMES              1319
#define IDC_EDIT3                       1320
#define IDC_EDIT_MAX_TIMES              1320
#define IDC_EDIT_TIMES_WEIGHT           1321
#define IDC_STATIC_AI_MANAGER           2001
#define IDC_TAB_FACE                    2002
#define IDC_EDIT_AI_HANGING_MIN_RATE    2010
#define IDC_EDIT_AI_HANGING_MAX_RATE    2011
#define IDC_EDIT_AI_CARRYSCORE_MINMULTI0 2012
#define IDC_EDIT_AI_CARRYSCORE_MAXMULTI0 2013
#define IDC_EDIT_AI_CARRYSCORE_LEVELRATE0 2014
#define IDC_EDIT_AI_CARRYSCORE_FLOATMINRATE0 2015
#define IDC_EDIT_AI_CARRYSCORE_FLOATMAXRATE0 2016
#define IDC_EDIT_AI_CARRYSCORE_MINMULTI1 2017
#define IDC_EDIT_AI_CARRYSCORE_MAXMULTI1 2018
#define IDC_EDIT_AI_CARRYSCORE_LEVELRATE1 2019
#define IDC_EDIT_AI_CARRYSCORE_FLOATMINRATE1 2020
#define IDC_EDIT_AI_CARRYSCORE_FLOATMAXRATE1 2021
#define IDC_EDIT_AI_CARRYSCORE_MINMULTI2 2022
#define IDC_EDIT_AI_CARRYSCORE_MAXMULTI2 2023
#define IDC_EDIT_AI_CARRYSCORE_LEVELRATE2 2024
#define IDC_EDIT_AI_CARRYSCORE_FLOATMINRATE2 2025
#define IDC_EDIT_AI_CARRYSCORE_FLOATMAXRATE2 2026
#define IDC_EDIT_AI_CARRYSCORE_MINMULTI3 2027
#define IDC_EDIT_AI_CARRYSCORE_MAXMULTI3 2028
#define IDC_EDIT_AI_CARRYSCORE_LEVELRATE3 2029
#define IDC_EDIT_AI_CARRYSCORE_FLOATMINRATE3 2030
#define IDC_EDIT_AI_CARRYSCORE_FLOATMAXRATE3 2031
#define IDC_EDIT_SERVICE_MODE           2032
#define IDC_EDIT_ENTER_TIME             2033
#define IDC_EDIT_LEAVE_TIME             2034
#define IDC_EDIT_ENTER_MIN_INTERVAL     2037
#define IDC_EDIT_ENTER_MAX_INTERVAL     2038
#define IDC_EDIT_LEAVE_MIN_INTERVAL     2039
#define IDC_EDIT_LEAVE_MAX_INTERVAL     2040
#define IDC_EDIT_TAKE_MIN_SCORE         2041
#define IDC_EDIT_TAKE_MAX_SCORE         2042
#define IDC_EDIT_SWITCH_MIN_INNINGS     2043
#define IDC_EDIT_SWITCH_MAX_INNINGS     2044
#define IDD_DLG_AI_MANAGER              3011
#define IDD_DLG_ROBOT_MANAGER           3011
#define IDD_DLG_ROBOT                   3011
#define IDD_ROOM_CONFIG                 3012
#define IDD_SERVER_VIEW                 3012
#define IDD_DLG_STOCK_MANAGER           3013
#define IDD_DLG_STOCK                   3013
#define IDD_DLG_CONFIG                  3014
#define IDC_PERCENT                     9013
#define IDC_FEE                         9015
#define IDC_WINRATE                     9019
#define IDC_FLEERATE                    9020
#define IDC_SCORELIMIT                  9021
#define IDC_BLACK                       9022
#define IDC_IPSET                       9023
#define IDC_WISPER                      9024
#define IDC_BASE_SCORE                  9024
#define IDC_ROOM_CHAT                   9026
#define IDC_GAME_CHAT                   9027
#define IDC_ENTER_ROOM                  9028
#define IDC_ENTER_GAME                  9029
#define IDC_PLAY_CHAT                   9030
#define IDC_BASEENSURE                  9031
#define IDC_ROBOT_ATTEND                9032
#define IDC_ROBOT_SIMULATE              9033
#define IDC_MEMBER_CHAT                 9034
#define IDC_LOOKON                      9035
#define IDC_LOOKON_CHAT                 9036
#define IDC_RECORD_GAME_SCORE           9037
#define IDC_IMMEDIATE_WRITE_SCORE       9038
#define IDC_VOICE_CHAT                  9039
#define IDC_OFFLINE_STANDUP             9042
#define IDC_FORCE_STANDUP               9043
#define IDC_DYNAMIC_JOINGAME            9044
#define IDC_DYNAMIC_JOINGAME2           9045
#define IDC_GAME_VIDEO                  9045
#define IDM_GIVE_UP_CONNECT             32777
#define IDM_DOWN_LOAD_CLIENT            32781
#define IDM_SET_COLLECTION              32783
#define IDM_ENTER_SERVER                32784
#define IDM_EXPAND_LIST                 32788
#define IDM_SHRINK_LIST                 32790
#define IDM_NULL_COMMAND                32792
#define IDM_DELETE_SERVER_ITEM          32794
#define IDM_SUTRA_VIEW_MODE             32796
#define IDM_DEFAULT_VIEW_MODE           32798
#define IDM_SWITCH_ACCOUNTS             32801
#define IDM_CREATE_WISPER               32813
#define IDM_COPY_USER_NAME              32814
#define IDM_SET_FRIEND                  32815
#define IDM_SET_DETEST                  32817
#define IDM_CANCEL_CHAT_USER            32819
#define IDM_SET_CHAT_USER               32820
#define IDM_SEARCH_ONLINE_USER          32821
#define IDM_INVITE_USER                 32822
#define IDM_SEE_LOCATION                32824
#define IDM_SHOW_USER_INFO              32826
#define IDM_SET_USER_NOTE               32827
#define IDM_USER_INFO_MANAGER           32830
#define IDM_LOOKON_USER                 32832
#define IDM_PLAY_GAME_TOGETHER          32834
#define IDM_SEND_BY_ENTER               32837
#define IDM_SEND_BY_CTRL_ENTER          32838
#define IDM_MORE_COLOR                  32840
#define IDM_AUTO_JOIN                   32843
#define IDM_SEARCH_TABLE                32844
#define IDM_ISSUE_MESSAGE               32858
#define IDM_MANAGER_SERVER              32859
#define IDM_MANAGER_TABLE_RULE          32860
#define IDM_MANAGER_ROBOT               32861
#define IDM_MANAGER_USER                32872
#define IDM_KILL_USER                   32874
#define IDM_DEFAULT_LINK                32876
#define IDM_WANG_TONG_LINK              32879
#define IDM_DIAN_XIN_LINK               32880
#define IDM_TREASURE_PAY                32886
#define IDM_SERVICE_CENTER              32887
#define IDM_TREASURE_CENTER             32888
#define IDM_MANAGER_SERVER_OPTION       32905
#define ID_32905                        32905
#define ID_DISMISS                      32906
#define ID_DISMISS_TABLE                32907
#define IDM_DISMISS_TABLE               32908
#define IDM_SEND_CARD					32909

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        441
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1320
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
