//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SkinResource.rc
//
#define IDB_PLAZA_FRAME_BL              139
#define IDB_PLAZA_FRAME_BM              140
#define IDB_PLAZA_FRAME_BR              141
#define IDB_PLAZA_FRAME_ML              142
#define IDB_PLAZA_FRAME_MR              143
#define IDB_PLAZA_FRAME_TL              144
#define IDB_PLAZA_FRAME_TM              145
#define IDB_PLAZA_FRAME_TR              146
#define IDB_PLAZA_BROWSER_ML            158
#define IDB_PLAZA_BROWSER_MR            159
#define IDB_PLAZA_BROWSER_TL            160
#define IDB_PLAZA_BROWSER_TM            161
#define IDB_PLAZA_BROWSER_TR            162
#define IDB_PLAZA_BROWSER_BL            163
#define IDB_PLAZA_BROWSER_BM            164
#define IDB_PLAZA_BROWSER_BR            165
#define IDB_BT_FRAME_ITEM_NORMAL        170
#define IDB_BT_FRAME_ITEM_AVTIVE        171
#define IDB_PLAZA_SERVER_ML             181
#define IDB_PLAZA_SERVER_MR             182
#define IDB_PLAZA_SERVER_TL             183
#define IDB_PLAZA_SERVER_TM             184
#define IDB_PLAZA_SERVER_TR             185
#define IDB_PLAZA_SERVER_BR             186
#define IDB_PLAZA_SERVER_BL             187
#define IDB_PLAZA_SERVER_BM             188
#define IDB_BT_PLAZA_BROWSER_HOME       191
#define IDB_BT_PLAZA_BROWSER_LAST       192
#define IDB_BT_PLAZA_BROWSER_NEXT       193
#define IDB_BT_PLAZA_BROWSER_RELOAD     194
#define IDB_BT_PLAZA_BROWSER_STOP       195
#define IDB_BT_PLAZA_FRAME_OPTION       197
#define IDB_BT_PLAZA_FRAME_BANK         198
#define IDB_PLAZA_TABLE_BL              209
#define IDB_PLAZA_TABLE_BM              210
#define IDB_PLAZA_TABLE_BR              211
#define IDB_PLAZA_TABLE_ML              212
#define IDB_PLAZA_TABLE_MR              213
#define IDB_PLAZA_TABLE_TL              214
#define IDB_PLAZA_TABLE_TM              215
#define IDB_PLAZA_TABLE_TR              216
#define IDB_PLAZA_CHAT_BL               218
#define IDB_PLAZA_CHAT_BM               219
#define IDB_PLAZA_CHAT_BR               220
#define IDB_PLAZA_CHAT_ML               221
#define IDB_PLAZA_CHAT_MR               222
#define IDB_PLAZA_CHAT_TL               223
#define IDB_PLAZA_CHAT_TM               224
#define IDB_PLAZA_CHAT_TR               225
#define IDB_BT_PLAZA_FRAME_MIN          235
#define IDB_BT_PLAZA_FRAME_CLOSE        236
#define IDB_BT_PLAZA_USER_INFO_MENU     238
#define IDB_BT_SHOW_GAME_LIST           241
#define IDB_BT_HIDE_GAME_LIST           242
#define IDB_BT_HIDE_USER_LIST           254
#define IDB_BT_SHOW_USER_LIST           255
#define IDB_BT_TABLE_FRAME_SEARCH_USER  256
#define IDB_BT_TABLE_FRAME_QUIT_GAME    257
#define IDB_BT_TABLE_FRAME_JOIN_MENU    259
#define IDB_BT_TABLE_FRAME_VIEW_MODE    260
#define IDB_BT_TABLE_FRAME_AUTO_JOIN    261
#define IDB_BT_PLAZA_CHAT_SEND_CHAT     262
#define IDB_BT_PLAZA_CHAT_SAVE_CHAT     263
#define IDB_BT_PLAZA_CHAT_CLEAN_SCREEN  264
#define IDB_BT_PLAZA_CHAT_COLOR_SET     265
#define IDB_BT_PLAZA_CHAT_EXPESSION     266
#define IDB_BT_PLAZA_CHAT_PHRASE        267
#define IDB_BT_PLAZA_CHAT_BUGLE         268
#define IDB_PLAZA_USER_INFO_L           281
#define IDB_PLAZA_USER_INFO_M           282
#define IDB_PLAZA_USER_INFO_R           283
#define IDB_BT_NORMAL_USER_NORMAL       287
#define IDB_BT_CUSTOM_USER_ACTIVE       288
#define IDB_BT_CUSTOM_USER_NORMAL       289
#define IDB_BT_NORMAL_USER_ACTIVE       290
#define IDB_BT_PLAZA_CHAT_CHAT_SHORT    307
#define IDB_BT_WHISPER_CLEAN_SCREEN     308
#define IDB_BT_WHISPER_COLOR_SET        309
#define IDB_BT_WHISPER_EXPESSION        310
#define IDB_BT_WHISPER_ADD_USER         311
#define IDB_BT_WHISPER_LEAVE_CHAT       314
#define IDB_BT_WHISPER_SEND_CONTROL     315
#define IDB_CHAT_WHISPER_BL             316
#define IDB_CHAT_WHISPER_BM             317
#define IDB_CHAT_WHISPER_BR             318
#define IDB_CHAT_WHISPER_ML             319
#define IDB_CHAT_WHISPER_MR             320
#define IDB_CHAT_WHISPER_TL             321
#define IDB_CHAT_WHISPER_TM             322
#define IDB_CHAT_WHISPER_TR             323
#define IDB_USER_WHISPER_BL             324
#define IDB_USER_WHISPER_BM             325
#define IDB_USER_WHISPER_BR             326
#define IDB_USER_WHISPER_ML             327
#define IDB_USER_WHISPER_MR             328
#define IDB_USER_WHISPER_TL             329
#define IDB_USER_WHISPER_TM             330
#define IDB_USER_WHISPER_TR             331
#define IDB_BT_WHISPER_MORE_FUNCTION    333
#define IDB_INPUT_WHISPER_BL            335
#define IDB_INPUT_WHISPER_BM            336
#define IDB_INPUT_WHISPER_BR            337
#define IDB_INPUT_WHISPER_ML            338
#define IDB_INPUT_WHISPER_MR            339
#define IDB_INPUT_WHISPER_TL            340
#define IDB_INPUT_WHISPER_TM            341
#define IDB_INPUT_WHISPER_TR            342
#define IDB_PLAZA_CHAT_CONTROL_BACK     344
#define IDB_BT_PLAZA_CHAT_CLOSE         345
#define IDB_BT_PLAZA_CHAT_CONTROL       346
#define IDB_SKIN_BUTTON_BACK            1000
#define IDB_SKIN_WND_CLOSE              1001
#define IDB_SKIN_WND_MAX                1002
#define IDB_BT_PLAZA_FRAME_NAVIGATION_1 1003
#define IDB_SKIN_WND_RESORE             1004
#define IDB_BT_PLAZA_FRAME_NAVIGATION_2 1005
#define IDB_BT_PLAZA_FRAME_NAVIGATION_3 1006
#define IDB_BT_PLAZA_FRAME_NAVIGATION_4 1007
#define IDC_HAND_CUR                    1010
#define IDB_BT_PLAZA_FRAME_NAVIGATION_5 1010
#define IDB_SKIN_WND_MIN                1011
#define IDB_PLAZA_TABLE_INVALID         1012
#define IDB_SKIN_WND_BL                 1013
#define IDB_SKIN_WND_BM                 1014
#define IDB_SKIN_WND_BR                 1015
#define IDB_SKIN_WND_ML                 1016
#define IDB_SKIN_WND_MR                 1017
#define IDB_SKIN_WND_TL                 1018
#define IDB_SKIN_WND_TM                 1019
#define IDB_SKIN_WND_TR                 1020
#define IDB_ENCIRCLE_TL                 1021
#define IDB_ENCIRCLE_TM                 1022
#define IDB_ENCIRCLE_TR                 1023
#define IDB_ENCIRCLE_BL                 1024
#define IDB_ENCIRCLE_BM                 1025
#define IDB_ENCIRCLE_BR                 1026
#define IDB_ENCIRCLE_ML                 1027
#define IDB_ENCIRCLE_MR                 1028
#define IDB_SKIN_MENU_FLAGS             1029
#define IDI_SKIN_ICON                   1030
#define IDB_PLAZA_TABLE_GROUND          1030
#define IDB_SKIN_HEADER_L               1032
#define IDB_SKIN_HEADER_M               1033
#define IDB_SKIN_HEADER_R               1034
#define IDB_COLLOCATE_BAR               1040
#define IDB_BT_TABLE_FRAME_CALL_MASTER  1042
#define IDB_SKIN_PREVIEW                1043
#define IDB_SKIN_COMBOBOX_THUMB         1045
#define IDB_BT_TABLE_FRAME_SERVER_MANAGE 1046
#define IDB_BT_PLAZA_FRAME_RESORE       1047
#define IDB_BT_PLAZA_FRAME_MAX          1048
#define IDB_SAFE_PROMPT                 1049
#define IDB_SAFE_BIND                   1050
#define IDB_ITEM_FRAME_BL               1052
#define IDB_ITEM_FRAME_BM               1053
#define IDB_ITEM_FRAME_BR               1054
#define IDB_ITEM_FRAME_ML               1055
#define IDB_ITEM_FRAME_MR               1056
#define IDB_ITEM_FRAME_TL               1057
#define IDB_ITEM_FRAME_TM               1058
#define IDB_ITEM_FRAME_TR               1059
#define IDB_BT_PLAZA_CHAT_STOP_CHAT     1060
#define IDB_BT_PLAZA_CHAT_RECV_CHAT     1061
#define IDB_BT_USER_COMPETITION         1063
#define IDB_MEMBER_SERVICE_BAR          1064
#define IDB_USER_SERVICE_BAR            1065
#define IDB_GAME_FRAME_BL               1069
#define IDB_GAME_FRAME_BM               1070
#define IDB_GAME_FRAME_BR               1071
#define IDB_GAME_FRAME_BT_CLOSE         1072
#define IDB_GAME_FRAME_BT_MAX           1073
#define IDB_GAME_FRAME_BT_MIN           1074
#define IDB_GAME_FRAME_BT_RESORE        1075
#define IDB_GAME_FRAME_ML               1076
#define IDB_GAME_FRAME_MR               1077
#define IDB_GAME_FRAME_TL               1078
#define IDB_GAME_FRAME_TM               1079
#define IDB_GAME_FRAME_TR               1080
#define IDB_GAME_USER_LIST_BL           1082
#define IDB_GAME_USER_LIST_BM           1083
#define IDB_GAME_USER_LIST_BR           1084
#define IDB_GAME_USER_LIST_ML           1085
#define IDB_GAME_USER_LIST_MR           1086
#define IDB_GAME_USER_LIST_TL           1087
#define IDB_GAME_USER_LIST_TM           1088
#define IDB_GAME_USER_LIST_TR           1089
#define IDB_BT_GAME_CHAT_BUGLE          1090
#define IDB_BT_GAME_CHAT_STOP_CHAT      1091
#define IDB_BT_GAME_CHAT_SEND_CHAT      1092
#define IDB_BT_GAME_CHAT_SAVE_CHAT      1093
#define IDB_BT_GAME_CHAT_PHRASE         1094
#define IDB_BT_GAME_CHAT_EXPESSION      1095
#define IDB_BT_GAME_CHAT_CONTROL        1096
#define IDB_BT_GAME_CHAT_COLOR_SET      1097
#define IDB_BT_GAME_CHAT_CLOSE          1098
#define IDB_BT_GAME_CHAT_CLEAN_SCREEN   1099
#define IDB_BT_GAME_CHAT_CHAT_SHORT     1100
#define IDB_GAME_CHAT_CONTROL_BACK      1101
#define IDB_BT_GAME_CHAT_MORE_FUNCTION  1102
#define IDB_BT_PLAZA_CHAT_MORE_FUNCTION 1103
#define IDB_GAME_CHAT_BL                1104
#define IDB_GAME_CHAT_BM                1105
#define IDB_GAME_CHAT_BR                1106
#define IDB_GAME_CHAT_ML                1107
#define IDB_GAME_CHAT_MR                1108
#define IDB_GAME_CHAT_TL                1109
#define IDB_GAME_CHAT_TM                1110
#define IDB_GAME_CHAT_TR                1111
#define IDB_GAME_USER_LIST_H_TR         1112
#define IDB_GAME_USER_LIST_H_TM         1113
#define IDB_GAME_USER_LIST_H_TL         1114
#define IDB_GAME_USER_LIST_H_MR         1115
#define IDB_GAME_USER_LIST_H_ML         1116
#define IDB_GAME_USER_LIST_H_BR         1117
#define IDB_GAME_USER_LIST_H_BM         1118
#define IDB_GAME_USER_LIST_H_BL         1119
#define IDB_GAME_CHAT_H_TR              1120
#define IDB_GAME_CHAT_H_TM              1121
#define IDB_GAME_CHAT_H_TL              1122
#define IDB_GAME_CHAT_H_MR              1123
#define IDB_GAME_CHAT_H_ML              1124
#define IDB_GAME_CHAT_H_BR              1125
#define IDB_GAME_CHAT_H_BM              1126
#define IDB_GAME_CHAT_H_BL              1127
#define IDB_GAME_USER_INFO_BL           1128
#define IDB_GAME_USER_INFO_BM           1129
#define IDB_GAME_USER_INFO_BR           1130
#define IDB_GAME_USER_INFO_ML           1131
#define IDB_GAME_USER_INFO_MR           1132
#define IDB_GAME_USER_INFO_TL           1133
#define IDB_GAME_USER_INFO_TM           1134
#define IDB_GAME_USER_INFO_TR           1135
#define IDB_GAME_BILL_L                 1136
#define IDB_GAME_BILL_M                 1137
#define IDB_GAME_BILL_R                 1138
#define IDB_BT_HIDE_GAME_BILL           1139
#define IDB_BT_SHOW_GAME_BILL           1140
#define IDB_PLAZA_USER_LIST_BL          1141
#define IDB_PLAZA_USER_LIST_BM          1142
#define IDB_PLAZA_USER_LIST_BR          1143
#define IDB_PLAZA_USER_LIST_TL          1144
#define IDB_PLAZA_USER_LIST_ML          1145
#define IDB_PLAZA_USER_LIST_TR          1146
#define IDB_PLAZA_USER_LIST_MR          1147
#define IDB_PLAZA_USER_LIST_TM          1148
#define IDB_BT_GAME_BAR_INVITE          1157
#define IDB_BT_GAME_BAR_MORE            1158
#define IDB_BT_GAME_BAR_OPTION          1159
#define IDB_BT_GAME_BAR_ALLOW_SOUND     1160
#define IDB_BT_GAME_BAR_HIDE_CONTROL    1161
#define IDB_BT_GAME_BAR_SHOW_CONTROL    1162
#define IDB_BT_GAME_BAR_LIMIT_SOUND     1163
#define IDB_GAME_BAR                    1164
#define IDB_BT_TABLE_FRAME_SECRET_TABLE 1165
#define IDB_PLAZA_TABLE_NUMBER          1166
#define IDB_BT_PLAZA_FRAME_COMPANION    1169
#define IDB_BT_PLAZA_FRAME_SYSTEM_AFFICHE 1170
#define IDB_BITMAP1                     1171
#define IDB_BT_PLAZA_FRAME_BUG_REPORT   1171
#define IDB_BITMAP2                     1172
#define IDB_BT_TABLE_FRAME_UNSECRET_TABLE 1172
#define IDB_BT_PLAZA_BASE_ENSURE        1173
#define IDB_BT_PLAZA_FRAME_BASE_ENSURE  1173
#define IDB_BUGLE_COLOR_SET             1174
#define IDB_BUGLE_EXPRESSION            1175
#define IDB_SKIN_SCROLL                 1176
#define IDB_DOWNLOAD_LOAD_LAST          1177
#define IDB_DOWNLOAD_LOAD_NEXT          1178
#define IDB_BT_GAME_CHAT_RECV_CHAT      11091

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1174
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
