//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ModuleManager.rc 使用
//
#define IDD_SERVICE_OPTION              102
#define IDD_SERVICE_OPTION2             103
#define IDD_SERVER_WIZARD_2             148
#define IDD_SERVER_WIZARD_1             150
#define IDC_SERVER_NAME                 1001
#define IDC_MODULE_LIST                 1002
#define IDC_NODE_ID                     1007
#define IDC_SERVER_TYPE                 1008
#define IDC_SERVER_TYPE2                1009
#define IDC_TABLE_GENRE                 1009
#define IDC_TABLE_COUNT                 1010
#define IDC_MAX_PLAYER                  1011
#define IDC_SERVER_PORT                 1012
#define IDC_SORT_ID                     1013
#define IDC_LIST_SERVICE_INFO           1013
#define IDC_CELL_SCORE                  1014
#define IDC_BT_MODIFY_SERVICE           1014
#define IDC_PROPORTION                  1015
#define IDC_VISIBLE_MASK_E              1015
#define IDC_EDIT_VISIBLE_EXTEND         1015
#define IDC_BT_ADD_SERVICE              1015
#define IDC_BT_DELETE_SERVICE           1016
#define IDC_DATABASE_ADDR               1017
#define IDC_DATABASE_NAME               1018
#define IDC_KIND_ID                     1022
#define IDC_SERVICE_ID                  1024
#define IDC_LESS_SCORE                  1025
#define IDC_RESTRICT_SCORE              1026
#define IDC_GAME_REVENUE                1027
#define IDC_SERVICE_ADDR                1028
#define IDC_SERVICE_DOMAIN              1029
#define IDC_BT_QUIT                     1029
#define IDC_E                           1030
#define IDC_EXPGAIN_RATE                1030
#define IDC_MAX_CONNECT                 1031
#define IDC_SERVICE_NAME                1034
#define IDC_LAST                        1065
#define IDC_NEXT                        1067
#define IDC_ITEM_FRAME                  1072
#define IDC_FINISH                      1076
#define IDC_PROMPT                      9000
#define IDC_CHECK1                      9001
#define IDC_IMMEDIATE_WRITE_SCORE       9001
#define IDC_VISIBLE_COMPUTER            9001
#define IDC_CHECK_REVIVE_ENABLED        9001
#define IDC_CHECK2                      9002
#define IDC_RECORD_GAME_SCORE           9002
#define IDD_DIALOG1                     9002
#define IDD_SERVER_WIZARD_CUSTOM        9002
#define IDC_ALLOW_LAST_SAMETABLE        9002
#define IDC_VISIBLE_MOBILE              9002
#define IDC_CHECK_SAFECARD_ENABLED      9002
#define IDD_SERVER_OPTION_CUSTOM        9002
#define IDC_CHECK3                      9003
#define IDC_RECORD_GAME                 9003
#define IDC_ALLOW_SAME_ADDRESS          9003
#define IDC_VISIBLE_FLASH               9003
#define IDC_RECORD_GAME_VIDEO           9003
#define IDC_CHECK4                      9004
#define IDC_FORBID_ROOM_CHAT            9004
#define IDC_CHECK_MEMBER_ORDER          9004
#define IDC_VISIBLE_EXTEND              9004
#define IDC_CHECK5                      9005
#define IDC_FORBID_ROOM_WISPER          9005
#define IDC_CHECK6                      9006
#define IDC_FORBIT_GAME_CHAT            9006
#define IDD_SERVER_MATCH                9006
#define IDC_CHECK7                      9007
#define IDC_TABLE_END                   9007
#define IDC_TABLE_END_IMMEDIATE         9007
#define IDD_SERVER_WIZARD               9007
#define IDC_CHECK8                      9008
#define IDC_TABLE_END_IMMEDIATE2        9008
#define IDC_DYNAMIC_JOIN_GAME           9008
#define IDD_MATCH_WIZARD                9008
#define IDC_EDIT1                       9009
#define IDC_DYNAMIC_CELL_SCORE          9009
#define IDD_MATCH_WIZARD_1              9009
#define IDC_PLAY_COUNT                  9009
#define IDC_CHECK11                     9009
#define IDC_CHECK_MATCH_USER            9009
#define IDC_EDIT_COUNT_INNINGS          9009
#define IDC_MIN_PLAYER_COUNT            9009
#define IDC_EDIT_SERVICE_PORT           9009
#define IDC_EDIT_SWITCH_COUNT           9009
#define IDC_EDIT2                       9010
#define IDC_DYNAMIC_CELL_SCORE2         9010
#define IDC_FORBIT_PLAY_CHAT            9010
#define IDC_SWITCH_TABLE_COUNT          9010
#define IDC_CHECK12                     9010
#define IDC_CHECK_EXPERIENCE            9010
#define IDC_EDIT_SERVICE_ADDR           9010
#define IDC_EDIT_INIT_SCORE             9010
#define IDD_MATCH_WIZARD_3              9010
#define IDC_DAY_OF_WEEK                 9010
#define IDC_CHECK9                      9011
#define IDC_MEMBER_CAN_CHAT             9011
#define IDC_MIN_PLAYCOUNT               9011
#define IDC_CHECK_SIGNUP_FEE            9011
#define IDC_EDIT_RESERVE_               9011
#define IDC_EDIT_RESERVE_RATIO          9011
#define IDC_DAY_OF_MONTH                9011
#define IDC_CHECK10                     9012
#define IDC_ALLOW_ENTER_Robot           9012
#define IDD_MATCH_IMMEDIATE             9012
#define IDC_INITIAL_BASE                9012
#define IDC_ALLOW_ROBOT_SIMULATE        9012
#define IDC_MIN_MATCH_USER              9012
#define IDC_CHECK_SIGNUP_FEE2           9012
#define IDC_CHECK_SIGNUP_SHARe          9012
#define IDC_CHECK_SIGNUP_SHARE          9012
#define IDC_CHECK_WECHAT_SHARE          9012
#define IDC_EDIT8                       9012
#define IDC_EDIT_INIT_BASE_SCORE        9012
#define IDC_EDIT_PLAY_COUNT             9012
#define IDC_RADIO1                      9013
#define IDC_PERCENT                     9013
#define IDC_FORBID_LOOKON               9013
#define IDC_START_USERCOUNT             9013
#define IDD_MAX_SIGNUP_USER             9013
#define IDD_MATCH_DISTRIBUTE            9013
#define IDC_RADIO_SINGLE_TURN           9013
#define IDC_RADIO_TOTAL_GRADES          9013
#define IDC_RADIO_IMMEDIATELY_MODE      9013
#define IDC_RADIO_INCREASE_MODE1        9013
#define IDC_CHECK_MATCH_TICKET          9013
#define IDC_EDIT_BASE_SCORE             9013
#define IDC_RADIO_SPECIALLY_GRADES      9014
#define IDC_RADIO_TOTAL_RANKING         9014
#define IDC_BT_MODIFY                   9014
#define IDC_DOUBLE_SCORE                9014
#define IDC_INITIAL_SCORE               9014
#define IDD_MATCH_SIGNUP                9014
#define IDC_RADIO4                      9014
#define IDD_MATCH_SIGNUP1               9014
#define IDC_MAX_PLAYCOUNT               9014
#define IDC_RADIO_DELAYWAIT_MODE        9014
#define IDC_RADIO_SCORE_INCREASE_MODE2  9014
#define IDC_RADIO_INCREASE_MODE2        9014
#define IDC_MAX_TABLE_COUNT             9014
#define IDC_CHECK_RESET_SCORE           9014
#define IDC_RADIO2                      9015
#define IDC_BT_DELETE                   9015
#define IDC_FEE                         9015
#define IDC_CAN_KICK_USER               9015
#define IDC_PARTAKE_MIN_GAMEUSER        9015
#define IDC_ROBOT_USERCOUNT             9015
#define IDC_RADIO_NOAMAL                9015
#define IDD_MATCH_SIGNUP2               9015
#define IDC_RADIO_SERVER                9015
#define IDC_RADIO_BEST_GRADES           9015
#define IDD_MIN_SIGNUP_USER             9015
#define IDD_END_DELAY_TIME              9015
#define IDC_RADIO_MATCH_LOCKTIME        9015
#define IDC_RADIO_AVERAGE_GRADES        9016
#define IDC_RADIO_WEBSITE               9016
#define IDC_RADIO_MEMBER_A              9016
#define IDC_RADIO3                      9016
#define IDC_BT_ADD                      9016
#define IDC_CAN_GAME_CHAT               9016
#define IDC_PARTAKE_MAX_GAMEUSER        9016
#define IDC_ROBOT_USERCOUNT2            9016
#define IDC_ROBOT_DELAYTIME             9016
#define IDD_MATCH_RANKING_MODE          9016
#define IDC_RADIO_MATCH_LOOP            9016
#define IDC_RADIO_MATCH_ROUND           9016
#define IDC_RADIO_AVERAGEEX_GRADES      9017
#define IDC_RADIO_MEMBER_B              9017
#define IDC_LIST_MATCH                  9017
#define IDC_CAN_ENTER_WITHOUTPD         9017
#define IDD_MATCH_REWARD                9017
#define IDC_RADIO_SIGNUP_FEE            9017
#define IDC_EDIT9                       9017
#define IDC_EDIT_START_INNING           9017
#define IDC_RADIO_EVERY_DAY             9017
#define IDC_RADIO_MEMBER_C              9018
#define IDC_DATE_BEGIN                  9018
#define IDC_FORBID_BUGLE                9018
#define IDD_SERVER_OPTION_1             9018
#define IDC_EDIT10                      9018
#define IDC_EDIT_INTERVAL_INNING        9018
#define IDC_RADIO_EVERY_WEEK            9018
#define IDC_RADIO_MEMBER_D              9019
#define IDC_TIME_BEGIN                  9019
#define IDC_FORBID_WINRATE              9019
#define IDC_RADIO5                      9019
#define IDC_RADIO_GOLD                  9019
#define IDD_SERVER_OPTION_2             9019
#define IDC_EDIT11                      9019
#define IDC_EDIT_INCREASE_RATIO         9019
#define IDC_EDIT_INCREASE_RATIO1        9019
#define IDC_EDIT_PLAY_COUNT2            9019
#define IDC_EDIT_MATCH_SCORE            9019
#define IDC_RADIO_MEDAL                 9020
#define IDC_DATE_END                    9020
#define IDC_MATCH_NAME                  9020
#define IDC_FORBID_FLEERATE             9020
#define IDC_RADIO6                      9020
#define IDC_ALLOW_SAME_TABLE            9020
#define IDD_SERVER_OPTION_3             9020
#define IDC_EDIT12                      9020
#define IDC_EDIT_MAX_BASE_SCORE         9020
#define IDC_RADIO_GOLD_1                9020
#define IDC_TIME_END                    9021
#define IDC_MATCH_PORT                  9021
#define IDC_FORBID_SCORELIMIT           9021
#define IDC_RADIO7                      9021
#define IDD_SERVER_OPTION4              9021
#define IDD_SERVER_OPTION_4             9021
#define IDC_RADIO_INGOT                 9021
#define IDC_RADIO_RESET_SCORE           9021
#define IDC_FORBID_BLACK                9022
#define IDC_ALLOW_SAME_MACHINE          9022
#define IDD_BATTLE_OPTION               9022
#define IDC_PLAY_COUNT2                 9022
#define IDC_RADIO8                      9022
#define IDC_RADIO_RESERVE_SCORE         9022
#define IDC_RADIO_EVERY_MONTH           9022
#define IDC_RADIO_INGOT_1               9022
#define IDC_FORBID_IPSET                9023
#define IDC_ALLOW_PLAYER_FIRST          9023
#define IDD_MATCH_ROUND                 9023
#define IDC_EDIT_INTERVAL_SECOND        9023
#define IDC_COMBO_MATCH                 9024
#define IDC_AVERTCHEAT_MODE             9024
#define IDC_FORBID_BATTLE_RECORD        9024
#define IDD_PROMOTE_OUT_GAME            9024
#define IDC_COMBO_DB                    9025
#define IDC_FORBID_SCORELIMIT2          9025
#define IDC_FORBID_PASSWORD             9025
#define IDC_MATCH_LIST                  9025
#define IDD_PROMOTE_FIXED_GAME          9025
#define IDC_EDIT_INCREASE_RATIO2        9025
#define IDC_EDT_MIN_ENTER               9026
#define IDC_COMBO_DB2                   9026
#define IDC_COMBO_CURRENCY              9026
#define IDC_LOAD_MATCH                  9026
#define IDC_FORBID_BIND_USER            9026
#define IDD_PROMOTE_FIXED_TABLE         9026
#define IDC_EDT_MAX_ENTER               9027
#define IDC_FORBID_SEND_GRADE           9027
#define IDD_MATCH_IMMEDIATE1            9027
#define IDD_MATCH_WIZARD_2              9027
#define IDC_EDT_MIN_MEMBER              9028
#define IDC_COMBO_DB_MATCH              9028
#define IDC_FORBID_BIND_USER2           9028
#define IDD_MATCH_TOURNAMENT            9028
#define IDC_EDT_MAX_MEMEBR              9029
#define IDD_MATCH_LOCKTIME              9029
#define IDC_CHECK_HIDE_INFO             9030
#define IDC_DELETE_MATCH                9030
#define IDC_CHECK_SAME_IP               9031
#define IDC_COMBO_LESS_PLAYER           9031
#define IDC_CREATE_MATCH                9031
#define IDC_ALLOW_ROBOT_ATTEND          9031
#define IDC_FORBID_WRITE_REWARD         9031
#define IDC_FORBID_BATTLE_REWARD        9031
#define IDC_FORBID_ROOM_WISPER2         9032
#define IDC_STATIC_PROPORTION           9032
#define IDC_TBLE_SHOW_BASE_SCORE        9032
#define IDC_FORBID_BLACK2               9032
#define IDC_OPTION_MATCH                9032
#define IDC_ALLOW_LARGESS_Subsidy       9032
#define IDC_STATIC_START_MODE           9033
#define IDC_ALLOW_OFFLINE_TRUSTEESHIP   9033
#define IDC_FORBID_OFFLINE_STANDUP      9033
#define IDC_FORBID_SAMEIP_NOTICE        9033
#define IDC_FORBID_SAMEIP_REMIND        9033
#define IDC_STATIC_LESS_USER            9034
#define IDC_HIDE_USER_INFO              9034
#define IDC_COMBO_MATCH_TYPE            9035
#define IDC_EDT_CREAT_TABLE_MEMBER      9035
#define IDC_EDT_CREATE_TABLE_MEMBER     9035
#define IDC_ALLOW_LARGESS_Subsidy2      9035
#define IDC_ALLOW_VOICE_CHAT            9035
#define IDC_COMBO_JOIN_CONDITION        9036
#define IDC_EDT_ENTER_TABLE_MEMEBR      9036
#define IDC_ALLOW_LARGESS_Subsidy3      9036
#define IDC_ALLOW_AGREEMENT_DISMISS     9036
#define IDC_COMBO_SUPERT                9037
#define IDC_FORBID_STANDUP_STANDUP      9037
#define IDC_FORBID_FORCE_STANDUP        9037
#define IDC_COMBO_SIGNUP_MODE           9038
#define IDC_ALLOW_AGREEMENT_DISMISS2    9038
#define IDC_MATCH_USER_BY_SCORE         9038
#define IDC_COMBO_MODULE_NAME           9038
#define IDC_MATCH_START_DATE            9039
#define IDC_COMBO_RELEVANCE_MATCH       9039
#define IDC_COMBO_RELATED_MATCH         9039
#define IDC_MATCH_END_DATE              9040
#define IDC_COMBO_MODULE_NAME2          9040
#define IDC_COMBO_SHOW_TYPE             9040
#define IDC_MATCH_START_TIME            9041
#define IDC_MATCH_END_TIME              9042
#define IDC_LIST_REWARD                 9043
#define IDC_MATCH_END_TIME2             9043
#define IDC_SINGUP_END_DATE             9043
#define IDC_SIGNUP_END_DATE             9043
#define IDC_ADD_REWARD                  9044
#define IDC_SINGUP_END_TIME2            9044
#define IDC_SINGUP_END_TIME             9044
#define IDC_SIGNUP_END_TIME             9044
#define IDC_SIGNUP_START_DATE           9045
#define IDC_MATCH_TIME                  9045
#define IDC_MATCH_LOCKTIME              9045
#define IDC_ADD_REWARD2                 9045
#define IDC_EDIT_MATCH_NAME             9046
#define IDC_SIGNUP_START_TIME           9046
#define IDC_MATCH_TIME_SPACE            9046
#define IDC_MATCH_INTERVAL              9046
#define IDC_EDIT_MATCH_FEE              9047
#define IDC_EDIT_SIGNUP_FEE             9047
#define IDC_DISTRIBUTE_MINCOUNT         9048
#define IDC_EDIT_USE_TICKET_COUNT       9048
#define IDC_DISTRIBUTE_INTERVAL         9049
#define IDC_EDIT_BUY_TICKET_AMOUNT      9049
#define IDC_MATCH_OPTION_FRAME          9050
#define IDC_EDIT_BUY_TICKET_COUNT       9050
#define IDC_RANKID                      9051
#define IDC_RANKID_START                9051
#define IDC_EDIT_SIGNUP_COUNT           9051
#define IDC_REWARD_GOLD                 9052
#define IDC_REWARD_DESCRIBE             9053
#define IDC_RANKID_END                  9053
#define IDC_INIT_SCORE                  9054
#define IDC_REWARD_INGOT                9054
#define IDC_REWARD_GOODS                9054
#define IDC_CULL_SCORE                  9055
#define IDC_REWARD_MEDAL                9055
#define IDC_REVIVE_TIMES                9056
#define IDC_REWARD_ENTITY               9056
#define IDC_REVIVE_FEE                  9057
#define IDC_MATCH_OPTION                9058
#define IDC_INIT_SCORE4                 9058
#define IDC_SAFECARD_FEE                9058
#define IDC_REVIVE_FEE2                 9058
#define IDC_REVIVE_SCORE                9058
#define IDC_REVIVE_MULTIPLE             9058
#define IDC_REVIVE_MULTI                9058
#define IDC_COMBO2                      9060
#define IDC_COMBO_FROM_MATCH            9060
#define IDC_SERVICE_KIND                9060
#define IDC_DATETIMEPICKER1             9061
#define IDC_DATE_MATCH_START            9061
#define IDC_EDIT3                       9062
#define IDC_EDIT_LOOP_PERIOD            9062
#define IDC_DATE_MATCH_END              9062
#define IDC_EDIT4                       9063
#define IDC_EDIT_SINGLE_RANK            9063
#define IDC_EDIT5                       9064
#define IDC_EDIT_TOTAL_RANK             9064
#define IDC_EDIT6                       9065
#define IDC_EDIT_EXPERIENCE             9065
#define IDC_MODIFY_REWARD               9066
#define IDC_DELETE_REWARD               9067
#define IDC_COMBO_MATCH_MODE            9067
#define IDC_MATCH_FRAME                 9068
#define IDC_SERVER_OPTION               9070
#define IDC_OK                          9071
#define IDC_COMBO_KIND_GAME             9071
#define IDC_SERVICE_ADDR1               9072
#define IDC_BT_SAVE_MATCH_OPTION        9072
#define IDC_BUTTON2                     9073
#define IDC_CANCEL                      9073
#define IDC_BT_SAVE_MATCH_OPTION2       9073
#define IDC_COMBO1                      9073
#define IDC_COMBO_PROMOTE_MODE          9073
#define IDC_COMBO_HOUR_2                9073
#define IDC_COMBO_MODULE                9073
#define IDC_SERVICE_PORT                9074
#define IDC_ADD_ROUND                   9074
#define IDC_COMBO_MINUTE_2              9074
#define IDC_BATTLE_LIST                 9075
#define IDC_DELETE_ROUND                9075
#define IDC_COMBO4                      9075
#define IDC_COMBO_SECOND_2              9075
#define IDC_PROMOTE_COUNT               9076
#define IDC_COMBO_HOUR_1                9076
#define IDC_PROMOTE_RULE                9077
#define IDC_COMBO_MINUTE_1              9077
#define IDC_LIST_ROUND                  9078
#define IDC_COMBO_SECOND_1              9078
#define IDC_ROUNDID                     9079
#define IDC_COMBO_HOUR_3                9079
#define IDC_MATCH_SCORE                 9080
#define IDC_MODIFY_ROUND                9080
#define IDC_COMBO_MINUTE_3              9080
#define IDC_SCORE_RULE2                 9081
#define IDC_EDIT_MATCH_CULL_SCORE       9081
#define IDC_EDIT_ELIMINATE_COUNT        9081
#define IDC_COMBO_SECOND_3              9081
#define IDC_PROMOTE_COUNT2              9082
#define IDC_MATCH_SCORE2                9082
#define IDC_EDIT_ELIMINATE_MULTI        9082
#define IDC_START_MIN_COUNT             9082
#define IDC_MATCH_VALID_DATE            9082
#define IDC_COMBO_HOUR_4                9082
#define IDC_EDIT_ELIMINATE_COUNT2       9083
#define IDC_EDIT_DISTRIBUTE_COUNT       9083
#define IDC_PLAYER_COUNT_MIN            9083
#define IDC_SCORE_RULE3                 9083
#define IDC_COMBO_MINUTE_4              9083
#define IDC_PLAYER_COUNT_MAX            9084
#define IDC_COMBO_SECOND_4              9084
#define IDC_START_MIN_COUNT2            9085
#define IDC_START_MAX_COUNT             9085
#define IDC_MATCH_TERMINATE_TIME        9085
#define IDC_MATCH_VALID_TIME            9085
#define IDC_MATCH_CUTOFF_TIME           9085
#define IDC_MATCH_CUTOFF_DATE           9086
#define IDC_MAX_PLAYER_COUNT            9087
#define IDC_RADIO_FEETYPE_GOLD          9088
#define IDC_COMBO_HOUR_5                9088
#define IDC_RADIO_FEETYPE_MEDAL         9089
#define IDC_COMBO_MINUTE_5              9089
#define IDC_RADIO_FEETYPE_INGOT         9090
#define ID_SERVICE_PORT                 9090
#define IDC_COMBO_SECOND_5              9090
#define IDC_SERVICE_LEVEL               9091
#define IDC_SERVER_LEVEL                9091
#define IDC_COMBO_HOUR_6                9091
#define IDC_MATCH_TYPE                  9092
#define IDC_COMBO_MINUTE_6              9092
#define IDC_COMBO_SECOND_6              9093
#define IDC_STATIC_MATCH_TYPE           9093
#define IDC_COMBO_WEEK_DAY              9094
#define IDC_COMBO_MONTH_DAY             9095
#define IDC_COMBO_MONTH_DAY2            9096
#define IDC_COMBO_YEAR_MONTH            9096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9014
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         9094
#define _APS_NEXT_SYMED_VALUE           9023
#endif
#endif
